### ISSUE TITLE
How to build the android to apk

### ISSUE THREAD

**Issue by pribadihcr** [jingpu/MDig#1]
Hi @jingpu 

How to install MDig app to android device?

many thanks

**Comment by jingpu** [comment]
The Android project code is all in Android/ folder.
We use NDK to build the native code, and build the whole project in Eclipse with Android SDK.

We setup the environment basically by following the lecture on "Native Android Development" in class. 
Here are the resources, which I think will be helpful.
http://web.stanford.edu/class/cs231m/lectures/lecture-3-native-dev-camera.pdf
https://github.com/cvgl-edu/cs231m-2015/wiki/Lecture-3#2-running-native-code-compiled-with-the-ndk
